# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The Capable One
email: jkenton@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Imagine if you can, a young boy is born in South Dakota (strains credulity, I know!). Then imagine that he moves to Iowa (certainly fiction territory, already). He goes to school a really long time. Then he moves to Maryland (the 7th state), and he lives there a long time, too! Well, that's just the unbelievable part!
baseurl: "/CapableOne" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jkenton
github_username:  jkenton

# Build settings
markdown: kramdown
